version: "3.7"

x-network:
  &network
  name: internal

x-restart:
  &restart unless-stopped

x-logging:
  &logging
  driver: journald

services:
  app:
    image: app_image
    command: './main'
    depends_on:
      - database
    env_file:
      - .env
    networks:
      internal:
    ports:
      - ${DOCKER_APP_PORT}:8080
    restart: *restart
    logging: *logging
  database:
    image: "postgres"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app_psql_data:/var/lib/psql
    networks:
      internal:
    ports:
      - ${DOCKER_DB_PORT}:5432
    restart: *restart
    logging: *logging

volumes:
  app_psql_data:

networks:
  internal:
    << : *network
    driver: bridge