version: "3.7"

x-network:
  &network
  name: roulette

x-restart:
  &restart unless-stopped

x-logging:
  &logging
  driver: journald

services:
  app:
    image: build_app
    command: './main'
    depends_on:
      - database
    env_file:
      - ./.env
    networks:
      roulette:
    ports:
      - ${DOCKER_APP_PORT}:8080
    restart: *restart
    logging: *logging
  database:
    image: "postgres"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app_psql_data:/var/lib/psql
    networks:
      roulette:
    ports:
      - "5432:5432"
    restart: *restart
    logging: *logging

volumes:
  app_psql_data:

networks:
  roulette:
    << : *network
    driver: bridge